steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["ci"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["install", "gatsby-cli"]
  - name: node:10.15.1
    entrypoint: "./node_modules/.bin/gatsby"
    args: ["build"]
    env:
      - "GATSBY_ACTIVE_ENV=${_GATSBY_ACTIVE_ENV}"
  - name: node:10.15.1
    entrypoint: npm
    args: ["install", "firebase-tools"]
  - name: node:10.15.1
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "${_TARGET_PROJECT_ID}"]
